### ISSUE TITLE
Source code doesn't work

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#671] opened 2022-03-08 21:55 UTC
**Can anyone upload a working copy of the source code?**
I have tried to compile and run the source package but it doesn't work at all. Too many errors, missing files, missing packages, impossible to work with.

**Uploading non working versions?**

Whoever upload the source code, Does he/she ever test what is uploaded?:

**Using Visual Studio 2019 doesn't work at all**
When publishing the SQL Version it crashes with tons of files missing.
What's wrong?

No explanation whatsoever of what nuget packages are required,

**System:**
 - YAF Version: v3.1.2.0
 - .NET Version: 4.72
 - SQL Server: 2019

**Comment by w8tcha** [comment] 2022-03-09 07:35
> Whoever upload the source code, Does he/she ever test what is uploaded?:

Of course its tested. You can see on the CI server that the source builds without any errors

https://ci.appveyor.com/project/YAFNET/yafnet

> I have tried to compile and run the source package but it doesn't work at all. Too many errors, missing files, missing packages, impossible to work with.

You need to do a package restore. 

The easist way is to turn on automatic restore during build by choosing Tools > Options > **NuGet Package Manager**. Under Package Restore options, select Allow NuGet to download missing packages.

![restore-01-autorestoreoptions](https://user-images.githubusercontent.com/722575/157393545-c1ac4134-1c96-47ca-a394-e9e42487ee58.png)
 
Or  In Solution Explorer, right click the solution and select **Restore NuGet Packages**.

> When publishing the SQL Version it crashes with tons of files missing.
What files are missing? I never use publish ?

**Comment by daprose-dotcom** [comment] 2022-03-09 18:47
Yes, that is interesting, as it compiles with no errors!!
But, when you attempt to publish either to a web site or a system folder, it crashes with tons of missing files.

The question would be, how to compile and/or publish a "release" package to a computer folder in the web server, 

Thank you for helping. I can't find any documentation that would direct me on this issue.

**Comment by w8tcha** [comment] 2022-03-10 02:17
What type of files are missing when you try to publish?

**Comment by w8tcha** [comment] 2022-03-10 13:29
I committed updated Visual Studio Project files. it should no publish successfully.

**Comment by daprose-dotcom** [comment] 2022-03-10 18:04
> 

While publishing ... the first missing file is package-lock.json  
I can't find it anywhere... if it is produced on the fly .. then the publishing process it is not working correctly.

I can publish other works with no problem while using VS 2019, but I can't publish YafNet.

**Comment by daprose-dotcom** [comment] 2022-03-10 18:16
I downloaded the code again, Compiled it successfully, published successfully, and now I am going to test it at:
http://daprose.com/forums, let see if it works! 

Thanks for the help. The problem seems to be corrected successfully. I am going to include you in my will so you can inherit all my debts. Thanks so much !!

**Comment by daprose-dotcom** [comment] 2022-03-10 18:35
Sorry!  I found more errors while trying to run the application

Line 28 and 29 of the recommended.web.config that I used as my web.config are the same:
<compilation debug="false" targetFramework="4.8" optimizeCompilations="false" />

Only one line is required. It crashed.

But now, after correcting that error, I get the following error:

An error occurred during the 
compilation of a resource required to service this request. Please 
review the following specific error details and modify your source code 
appropriately.

Compiler Error Message: CS0101: The namespace 'Resources' already contains a definition for 'Install'

Source Error:
         
Line 10: //------------------------------------------------------------------------------ Line 11:  Line 12: namespace Resources.Install { Line 13:     using System;

Source File: c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\forums\276e2450\e630afe\App_GlobalResources.ejnwyptc.1.cs    Line: 12

**Comment by daprose-dotcom** [comment] 2022-03-10 18:38
On the third run, I get this error:

Line 24:     [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] Line 25:     [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] Line 26:     public class Install { Line 27:          Line 28:         private static global::System.Resources.ResourceManager resourceMan;
--
Source File:
c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET 
Files\forums\276e2450\e630afe\App_GlobalResources.6lmlavyx.1.cs
Line:  26

**Comment by w8tcha** [comment] 2022-03-10 18:49
I fixed the issue with the package-lock.json and the duplicate entry in the recommend.web.config. 

The other errors i cant reproduce.  I need to do some more testing.

**Comment by daprose-dotcom** [comment] 2022-03-10 18:53
Feel free to access the installed application at:
http://daprose.com/forums

If you need TeamViewer access, let me know.

**Comment by daprose-dotcom** [comment] 2022-03-10 19:32
Now I get a different Error:

            <h2> <i>Could not load file or assembly 'Newtonsoft.Json, 
Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or 
one of its dependencies. The system cannot find the file specified.</i> </h2></span>

            <b> Description: </b>An unhandled exception occurred during 
the execution of the current web request. Please review the stack trace 
for more information about the error and where it originated in the 
code.

            <br><br>

            <b> Exception Details: </b>System.IO.FileNotFoundException: 
Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, 
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its 
dependencies. The system cannot find the file specified.<br><br>

            <b>Source Error:</b> <br><br>

An unhandled exception was generated during the execution of the current  web request. Information regarding the origin and location of the  exception can be identified using the exception stack trace below.

[FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.]

[FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.]
   System.Net.Http.Formatting.BaseJsonMediaTypeFormatter..ctor() +0
   System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor() +73
   System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters() +55
   System.Web.Http.HttpConfiguration.DefaultFormatters(HttpConfiguration config) +34
   System.Web.Http.HttpConfiguration..ctor(HttpRouteCollection routes) +382
   System.Web.Http.<>c.<CreateConfiguration>b__11_0() +94
   System.Lazy`1.CreateValue() +734
   System.Lazy`1.LazyInitValue() +189
   System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback) +53
   YAF.Core.Context.YafHttpApplication.Application_Start(Object sender, EventArgs e) in C:\Users\Admin\source\repos\yafsrc\YAF.Core\Context\YAFHttpApplication.cs:162

[HttpException (0x80004005): Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +546
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +171
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +255
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +347

[HttpException (0x80004005): Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737

**Comment by kulum** [comment] 2022-03-10 21:03
Oh course we can brother but what do you think about the language to go is its semantics is okay?

**Comment by kulum** [comment] 2022-03-10 21:04
Look in 75 string, that's some mistake

**Comment by w8tcha** [comment] 2022-03-11 02:00
Does the file Newtonsoft.json.dll exist in the bin folder?

**Comment by daprose-dotcom** [comment] 2022-03-11 03:28
My friend! After so many tries and errors, I got it to work!

Yes, the file exists!

See it for yourself at http://daprose.com/forums 

What I did is to remove all Nuget packages, reinstall them one by one. Then I remove the reference of the missing file: package-lock.json

I published it, and this time it went to a 100% without errors. 

I can see the main page now at http://daprose.com/forums but the last home place will be on another site I am preparing right now.   I have not logged in it as yet to see how the admin pages work but that would be my next step. Sorry I gave you so many headackes

Well, so far it works, but it took me many hours of work and many many attempts to figure it out. It should not be that way.

Cheers my friend. Do you need a copy of the project?

**Comment by w8tcha** [comment] 2022-03-11 03:57
Thanks for your feedback. Yes your right those issues should not happen on a new install. I already made the changes so this will no longer happen in 3.1.3.

I never use the publish function. But now I will include in the testing before a release.

**Comment by daprose-dotcom** [comment] 2022-03-11 04:29
I need to show only the categories on the main page, (not the forums), once they select an specific category, then we should display the forums available in that category selected. 

Can you advice me what and where I have to change to make this possible?

It will be better having the option on the board settings on how each administrator want this to work.

**Comment by w8tcha** [comment] 2022-03-11 04:46
If I understand you correctly you mean with main page not 

http://daprose.com/forums/ the forum main page but instead you mean the site main page...

http://daprose.com/

Correct?

**Comment by daprose-dotcom** [comment] 2022-03-11 04:50
Another severe error happened while writing a new topic,

Server Error in '/forums' Application.
Access to the path 'C:\inetpub\wwwroot\aspx-daprose-yaf\App_Data\search_index' is denied. 

The folder App_Data does not exist, much worst any files in it. I can not write any topics . Why is it looking for a search_index file when writing a new topic?

I was able to create a new category and a new forum, but I can not post any topics in this version. This is a severe error. So much work for nothing. ... I do not know how to fix this error and I am in love with this version I manage to publish after so much work. Can you help me to correct this error and not to delete nor replace this versions?

**Comment by daprose-dotcom** [comment] 2022-03-11 04:54
> 

I need YafNeT main page to show only the Forum Categories on the main page, (not the forums themselves). 

Once the client selects any specific category, then we should display the forums available in that specific category selected. 

In other words, we should not display any forums on the YafNet main page but only the list of Categories.

Can you advice me what and where I have to change to make this possible?

It will be better having that option on the board settings page, so each administrator can decide how to display categories and forums on the main page..

As a sample, please visit http://mybbs.org/, That is how I wanted it to work!

**Comment by w8tcha** [comment] 2022-03-11 05:07
> Another severe error happened while writing a new topic,
> 
> 
> 
> Server Error in '/forums' Application.
> 
> Access to the path 'C:\inetpub\wwwroot\aspx-daprose-yaf\App_Data\search_index' is denied. 
> 
> 
> 
> The folder App_Data does not exist, much worst any files in it. I can not write any topics . Why is it looking for a search_index file when writing a new topic?
> 
> 
> 
> I was able to create a new category and a new forum, but I can not post any topics in this version. This is a severe error. So much work for nothing. ... I do not know how to fix this error and I am in love with this version I manage to publish after so much work. Can you help me to correct this error and not to delete nor replace this versions? 

It should work if you create the app_data dolce. Also the iis user needs to have write access

**Comment by daprose-dotcom** [comment] 2022-03-11 05:45
Yes, that worked great! I created the folder and gave writing privileges. This time it worked fine. We are in a good path to success!! Youjuuuu!!!

**Comment by daprose-dotcom** [comment] 2022-03-11 05:51
Ok I created a new topic and this time NO ERRORS. 
However, a moderate message came out with a font color WHITE on a WHITE background. Impossible to read unless I selected the content on the whole box.  Must fix that error.

**Comment by daprose-dotcom** [comment] 2022-03-11 05:57
When I click on the "TEAM" link on the main menu, I get the following ERROR:

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): DataBinding: 'YAF.Types.Models.User' does not contain a property with the name 'ModeratorID'.
   at System.Web.UI.DataBinder.GetPropertyValue(Object container, String propName)
   at System.Web.UI.DataBinder.Eval(Object container, String[] expressionParts)
   at ASP.pages_team_ascx.__DataBinding__control25(Object sender, EventArgs e) in c:\inetpub\wwwroot\aspx-daprose-yaf\Pages\Team.ascx:line 66
   at System.Web.UI.Control.OnDataBinding(EventArgs e)
   at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
   at System.Web.UI.Control.DataBindChildren()
   at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
   at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
   at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
   at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
   at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
   at System.Web.UI.Control.DataBindChildren()
   at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.default_aspx.EndProcessRequest(IAsyncResult ar) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\forums\276e2450\e630afe\App_Web_vd31j4hl.2.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by w8tcha** [comment] 2022-03-11 06:00
Can you please open new issue reports for different errors. It impossible to reply!

**Comment by daprose-dotcom** [comment] 2022-03-11 08:55
Done. I have created a new issue in the BUGS forum as you commanded me HER CAPTAIN.

Well, then this thread is concluded, closed for now as Application seem to be running and I am ready to rock-n-roll ..

Now ... about the how to make the categories only show up on the main page, without the Forums and Topics, like in a compressed mode, please direct me where to start.  Thanks you so much for your help.

**Comment by daprose-dotcom** [comment] 2022-03-11 11:59
Thank you anyway. I think I found it. Now it works as I want it. 
Please see it at: http://daprose.com/forums 

That, to me, is the way it is supposed to work, but still there is another change I need to make, No topics should be displayed unless the user selects a topic.

The active topics box at the bottom of the categories is fine. I like that, bot no other topics should be displayed unless the user selects a Category, then a specific Forum.  

**Thank you Ingo w8tcha, you are doing a great job!**

I am considering to talk to God and ask him to double your income in one shot!

**Closed** 2022-03-11 14:18 UTC
Labels: Bug
