### ISSUE TITLE
Browsing as "Guest" gives too much http request data

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#527] opened 2020-01-20 19:17 UTC
The "Active Topics" while browsing as a Guest returns too much data, exceeding the max http request length.

Visit as guest at https://forum.m-users.net  
Select "Active topics"
Change the time period to a longer time - 2 days, a week or all or such...

**Expected behavior**
A list of topics...  But... 

**Screenshots**
![image](https://user-images.githubusercontent.com/5246746/72751937-37da4600-3bc1-11ea-8963-7b7f52b6cfc6.png)

**System (please complete the following information):**
- YAF Version: 2.31 BETA 202001150940
- .NET Version 4.7.2
- SQL Server 2019
- Win Server 2016 Standard

**Suggestion**
Maybe added paging or a "copy" of the "Active Discussions"  length setting without time ago selection would do the trick? After all - what's the real difference between "Active Topics" and "Active Discussions" regarding guest viewing (except only seeing "public" topics) ?   
*

**Comment by w8tcha** [comment] 2020-01-22 08:24
> what's the real difference between "Active Topics" and "Active Discussions" regarding guest viewing (except only seeing "public" topics) 

The difference is that active topics shows more data. and the page has paging. 

i can't reproduce the issue on your site, But i guess reduce the items (in the host settings) from  20 to 10 or 5 would fix the problem. Or hide that page entirely for guests

**Comment by JP58** [comment] 2020-01-27 19:29
I think guests should be disabled from that page, to be honest...

**Comment by w8tcha** [comment] 2020-01-29 14:35
I already committed the changes. Page is no longer visible for guests

**Closed by w8tcha** 2020-01-29 14:35 UTC
Labels: Bug
