### ISSUE TITLE
cannot post anymore

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#558] opened 2020-04-16 10:02 UTC
**Describe the bug**
After yesterday's sync I get this error for every posted message (new or edit)
![image](https://user-images.githubusercontent.com/18015672/79442759-41652580-7fd9-11ea-9505-69cdb3bc7f89.png)

I cleaned solution and rebuild. 
Thanks

**Comment by w8tcha** [comment] 2020-04-16 15:21
Are you sure you updated and recompiled all files?  I can't reproduce the issue

**Comment by webmedia1012** [comment] 2020-04-16 18:18
I 'm having the same issue folks. Where do I find the injection for this? Also the CKEditor keeps on giving me Null value exceptions and it wouldn't load. - Thank you

**Comment by w8tcha** [comment] 2020-04-17 04:53
> I 'm having the same issue folks. Where do I find the injection for this? Also the CKEditor keeps on giving me Null value exceptions and it wouldn't load. - Thank you

Please open a new issue withthe full error message for the ckeditor

**Comment by AlbertoP57** [comment] 2020-05-04 15:16
Still here. (Maybe) Found it:

I went to: 
**Spam Settings**
**Choose a SPAM Service for Automatically SPAM Checking**
set to **Disabled**
**Saved**.
It saved posts

Then, I put **Internal Spam Check Words back** and it still continue works. 
Dont know the reason but it seems to works.

TY

**Comment by w8tcha** [comment] 2020-05-05 03:59
Saving the host settings, reloads the boardsettings. 

I guess we an close the issue

**Closed** 2020-05-05 03:59 UTC
Labels: Bug
