### ISSUE TITLE
CKEditor isn't showing on YAF NET 2.2.4.20

### ISSUE THREAD

**Issue by osirisAman** [YAFNET/YAFNET#664] opened 2021-12-04 17:50 UTC
Goodevening,

I set on the CKEditor instead of the normal BB Code editor but now the textarea isn't showing anymore. 

How can I fix it? 

Thanks :)

**Comment by w8tcha** [comment] 2021-12-04 22:36
Can you check the browser console for java script errors?

Also please consider an update to the latest version!

**Comment by osirisAman** [comment] 2021-12-04 23:04
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ckeditor.js:260 Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.detect (ckeditor.js:260)
    at Object.load (ckeditor.js:260)
    at q (ckeditor.js:279)
    at ckeditor.js:279
    at b (ckeditor.js:565)
    at Object.loadPart (ckeditor.js:567)
    at l (ckeditor.js:279)
    at a.<anonymous> (ckeditor.js:278)
    at a.q (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:12)


That's what the console says..

And yeah but I am in love with the older theme. If theres a way to export my theme to the newer vers I will do it!

**Comment by w8tcha** [comment] 2021-12-04 23:54
The issue is fixed in the current version. So upgrading is the only option.

**Comment by osirisAman** [comment] 2021-12-04 23:56
Okay, thank you! :)

**Comment by w8tcha** [comment] 2021-12-05 02:30
Regarding the new themes in bootstrap. It's not possible to import the old themes.

However with bootstrap it's much easier to create a new theme.

Also there are 25 themes already included.

**Closed** 2021-12-12 09:04 UTC
Labels: Bug
