### ISSUE TITLE
upgrading from v2

### ISSUE THREAD

**Issue by MROSSFTEK** [YAFNET/YAFNET#1097] opened 2024-03-05 19:38 UTC
I have an OLD forum i want to upgrade to v 3.2.2
its running V2.0 of YAF.. i am having a bunch of errors and issues.
is there a proper upgrade path to get to the latest revision?

**Comment by w8tcha** [comment] 2024-03-05 20:04
You should be able to directly upgrade. What errors are you getting?

**Comment by MROSSFTEK** [comment] 2024-03-05 20:05
the one im currently stuck on is 
'yaf_Message' is not a constraint.
Could not drop constraint. See previous errors

**Comment by MROSSFTEK** [comment] 2024-03-05 20:08
my errors started with this, looking direclty at my old 2.0 sql database
<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="font-family: Verdana; font-weight: normal; font-size: 18pt; color: red;">Server Error in '/' Application.<hr width="100%" size="1" color="silver"></h1><h2 style="font-family: Verdana; font-weight: normal; font-size: 14pt; color: maroon;"><i>Cannot alter or drop column 'Message' because it is enabled for Full-Text Search.</i></h2></span><span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif " style="color: rgb(0, 0, 0); font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Description:<span> </span></b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Exception Details:<span> </span></b>System.Data.SqlClient.SqlException: Cannot alter or drop column 'Message' because it is enabled for Full-Text Search.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Source Error:</b><br><br>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--


</font>
</body>
</html>

**Comment by w8tcha** [comment] 2024-03-06 08:18
First of all I hope you made a db backup before the upgrade. It looks like there is an issue with removing the fulltext support in the db. I cannot directly test it, i tried to fix in in 3.2.3
here is a beta
[YAF.SqlServer-v3.2.3-Upgrade.zip](https://github.com/YAFNET/YAFNET/files/14506825/YAF.SqlServer-v3.2.3-Upgrade.zip)

you need to restore the db first.

**Comment by MROSSFTEK** [comment] 2024-03-06 13:23
did a fresh backup\restore and now i see this.. i can confirm those dbo tables do exist
Server Error in '/' Application.
The object '[dbo].["dbo"."yaf_Message"]' does not exist in database '2.0' or is invalid for this operation.
The object '[dbo].["dbo"."yaf_Topic"]' does not exist in database '2.0' or is invalid for this operation.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: The object '[dbo].["dbo"."yaf_Message"]' does not exist in database '2.0' or is invalid for this operation.
The object '[dbo].["dbo"."yaf_Topic"]' does not exist in database '2.0' or is invalid for this operation.

**Comment by w8tcha** [comment] 2024-03-06 13:38
Argh sorry dublicate dbo

[YAF.SqlServer-v3.2.3-Upgrade.zip](https://github.com/YAFNET/YAFNET/files/14510557/YAF.SqlServer-v3.2.3-Upgrade.zip)

Updated!

**Comment by MROSSFTEK** [comment] 2024-03-06 13:47
ok for some reason im having the exact same error.
ill wait until my brain wakes up and ill do it all from scratch again LOL

**Comment by MROSSFTEK** [comment] 2024-03-06 17:43
same error as above
Server Error in '/' Application.
The object '[dbo].["dbo"."yaf_Message"]' does not exist in database '2.0' or is invalid for this operation.
The object '[dbo].["dbo"."yaf_Topic"]' does not exist in database '2.0' or is invalid for this operation.

**Comment by w8tcha** [comment] 2024-03-07 06:17
Are you sure you updated all dlls? i double checked and this is not correct error output

**Comment by MROSSFTEK** [comment] 2024-03-07 13:05
yeah i went folder by folder and followed the upgrade instructions on the main website

**Comment by MROSSFTEK** [comment] 2024-03-07 14:21
i went back to the files from the original upgrade, not the one you linked, just to see if it would make a difference.

Server Error in '/' Application.
Cannot alter or drop column 'Message' because it is enabled for Full-Text Search.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Cannot alter or drop column 'Message' because it is enabled for Full-Text Search.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by w8tcha** [comment] 2024-03-07 22:51
Okay another update, now it should be correct

[YAF.SqlServer-v3.2.3-Upgrade.zip](https://github.com/YAFNET/YAFNET/files/14530996/YAF.SqlServer-v3.2.3-Upgrade.zip)

**Comment by MROSSFTEK** [comment] 2024-03-08 13:24
new error
Server Error in '/' Application.
Column "Message" is not full-text indexed.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Column "Message" is not full-text indexed.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[SqlException (0x80131904): Column "Message" is not full-text indexed.]

**Comment by w8tcha** [comment] 2024-03-09 02:50
Thats strange, this should work. Can you execute sql commands directly so its more easy to test the commands and find a solution?

If yes can you execute the commands

```sql
ALTER FULLTEXT INDEX ON [dbo].[yaf_Message] DISABLE
ALTER FULLTEXT INDEX ON [dbo].[yaf_Message] DROP (Message)
```

**Comment by MROSSFTEK** [comment] 2024-03-11 12:26
yup.. tried that.. i get one error running those
Msg 102, Level 15, State 1, Line 2
Incorrect syntax near 'DROP'.

**Comment by MROSSFTEK** [comment] 2024-03-11 12:36
if i go in via sql and enable full text indexing on the yaf.message table's Message column, i then get the same message on the yaf.topic's topic column.
i set both of them for full text indexing via sql manager, then refresh the page, i get
'yaf_Message' is not a constraint.
Could not drop constraint. See previous errors.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: 'yaf_Message' is not a constraint.
Could not drop constraint. See previous errors.

i refresh and im back to the  column message is not full indexed.

im wondering if there's a sql command i need to run against the entire database to fix all full text indexing??? just a gues

**Comment by w8tcha** [comment] 2024-03-11 19:54
According to the documentation 

https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-fulltext-index-transact-sql?view=sql-server-ver16

This would be the correct statement to drop the index on column message on table yaf_message 

ALTER FULLTEXT INDEX ON tableName  DROP (ColumnName)

**Comment by MROSSFTEK** [comment] 2024-03-11 19:57
ive even gone in via sql mgmt and enabled full text search on those columns.. and relaunch the site, eventually get the same error about the constraint.. then the error about message not full context. 
i have access to sql mgmt studio on the server itself.

**Comment by MROSSFTEK** [comment] 2024-03-11 20:02
i manually made that table and column full indexed. then re ran those commands, and it was successful.
however im still getting an error on site/install that 'message' is not full text indexed
Server Error in '/' Application.
Column "Message" is not full-text indexed.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Column "Message" is not full-text indexed.

**Comment by MROSSFTEK** [comment] 2024-03-11 20:08
if i go in via sql and set that column to be full indexed, the next error i get is
Column "Topic" is not full-text indexed.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.


i go to yaf_topic and set that column to be full indexed it goes back to the constraint error.
running this on a win 2019 standard server in a vmware VM if that makes any difference.

**Comment by w8tcha** [comment] 2024-03-12 07:00
I finally had some time to install full text search on my test sql server. And updated my YAF 1.9.5 test database. i was able to reproduce the issue.

I uploaded another BETA of 3.2.3

[YAF.SqlServer-v3.2.3-Upgrade.zip](https://github.com/YAFNET/YAFNET/files/14568461/YAF.SqlServer-v3.2.3-Upgrade.zip)

**Comment by MROSSFTEK** [comment] 2024-03-12 12:32
progress.. i think.
i restored my 2.0 database to a new database. 
copied my old directory to a new directory
followed the upgrade instructions, edited my web.config and app.config per the upgrade instructions.
this time i get this error.. and i dont know what file its finding the syntax error on 

Server Error in '/' Application.
Incorrect syntax near ';'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Incorrect syntax near ';'.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[SqlException (0x80131904): Incorrect syntax near ';'.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +3318656
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +334
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4289
   System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) +1339
   System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) +434
   System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +391
   ServiceStack.OrmLite.OrmLiteExecFilter.Exec(IDbConnection dbConn, Func`2 filter) in C:\YAFNET\yafsrc\ServiceStack\ServiceStack.OrmLite\OrmLiteExecFilter.cs:180
   YAF.Core.Migrations.Migration80.UpgradeTable(IRepository`1 repository, IDbCommand dbCommand) +214
   YAF.Core.Migrations.<>c__DisplayClass2_0.<MigrateDatabase>b__1(IDbCommand dbCommand) +1501
   YAF.Core.Data.DbAccessBase.Execute(Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction) +214
   YAF.Core.Migrations.Migration80.MigrateDatabase(IDbAccess dbAccess) +316
   YAF.Core.Services.UpgradeService.Upgrade() +486
   YAF.Core.Services.Startup.StartupInitializeDb.RunService() +446
   YAF.Core.Services.Startup.BaseStartupService.Run() +37
   System.Collections.Generic.List`1.ForEach(Action`1 action) +101
   YAF.Core.Extensions.IHaveServiceLocatorExtensions.RunStartupServices(IHaveServiceLocator serviceLocator) +490
   YAF.Core.Context.YafHttpApplication.Session_Start(Object sender, EventArgs e) +18
   System.Web.SessionState.SessionStateModule.CompleteAcquireState() +375
   System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) +1257
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +703
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +75
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +158

**Comment by w8tcha** [comment] 2024-03-12 13:58
Looks like the web.config is not correctly updated, did you use the migration tool?

the entry 

` <add tagPrefix="YAF" namespace="YAF.Classes"/>`

needs to be removed

**Comment by MROSSFTEK** [comment] 2024-03-12 14:00
yes i used the migration tool. 
i re did it a few times already and now im running into this error every time.
Server Error in '/' Application.
Incorrect syntax near ';'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Incorrect syntax near ';'.

**Comment by w8tcha** [comment] 2024-03-12 20:11
Change the depend assembly to...

` <dependentAssembly>
        <assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51"/>
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>`

**Comment by w8tcha** [comment] 2024-03-13 06:25
[YAF.SqlServer-v3.2.3-Upgrade.zip](https://github.com/YAFNET/YAFNET/files/14583239/YAF.SqlServer-v3.2.3-Upgrade.zip)

I uploaded another test version, issue with 

> Incorrect syntax near ';'.

should be fixed.

**Comment by w8tcha** [comment] 2024-03-13 12:35
Sorry i can not update the migrationtool at the moment. Thats why you need to manually change the entries in the web.config

change 

```xml
 <dependentAssembly>
	 <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
	 <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
```

and 
```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51"/>
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.webServer>
```

**Comment by w8tcha** [comment] 2024-03-13 12:54
you have two duplicate entries for System.Diagnostics.DiagnosticSource. Sorry i was not clear replace the existing 

```xml
<dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.2" newVersion="7.0.0.2" />
      </dependentAssembly>
```

with 

```xml
<dependentAssembly>
	 <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
	 <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
```


so in your case remove the 

```xml
<dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.2" newVersion="7.0.0.2" />
      </dependentAssembly>
```

and only keep the 

```xml
<dependentAssembly>
	 <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
	 <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
```

**Comment by MROSSFTEK** [comment] 2024-03-13 12:54
yeah just saw that.. im a dope.. ok
fixed that now i get this error
Could not find a part of the path 'C:\YAF\V323\install\install\mssql\upgrade\identity\upgrade.sql'.

**Comment by MROSSFTEK** [comment] 2024-03-13 12:55
dunno why its going after install\install\mssql

**Comment by w8tcha** [comment] 2024-03-13 13:03
i cannot reproduce it in the code it looks for "install/mssql/upgrade/identity/upgrade.sql" i change it to "~/install/mssql/upgrade/identity/upgrade.sql" then it should pick it up from the right path

updated test build...

[YAF.SqlServer-v3.2.3-Upgrade.zip](https://github.com/YAFNET/YAFNET/files/14588012/YAF.SqlServer-v3.2.3-Upgrade.zip)

**Comment by MROSSFTEK** [comment] 2024-03-13 13:18
re did it from 'scratch'.. the install page loads! awesome!!

**Comment by MROSSFTEK** [comment] 2024-03-13 13:34
the upgrade looks like it completed.. but it wont let me login to the board. i put in my username and pass , click "Forum Login", the box just sits on the screen and does not login.

**Comment by MROSSFTEK** [comment] 2024-03-13 14:46
i got logged in. i had to reset my password using the lost password screen. im in.
now im just working on the look and feel. i changed out the main logo, but it looks like between the old version i had, and this new one, the logo gets squished to be really small. 
I also had the icons changed for new topics, old topics, etc. now we have the default ones.
The shoutbox was removed at some point durring YAF's development, which is a feature i really liked.

**Comment by MROSSFTEK** [comment] 2024-03-13 16:10
the forum is up and running! i altered some of the code on the pages as i liked to have 2 colums instead of scrolling all the way down to the bottom for the stats, and recent posts and such.
check it out if you like. i havent upgraded it or promoted the forum in YEARS.. but i may make a bigger effort now LOL
https://silveradoss.net/

**Comment by w8tcha** [comment] 2024-03-13 19:24
> the forum is up and running! i altered some of the code on the pages as i liked to have 2 colums instead of scrolling all the way down to the bottom for the stats, and recent posts and such.
> 
> check it out if you like. i havent upgraded it or promoted the forum in YEARS.. but i may make a bigger effort now LOL
> 
> https://silveradoss.net/
> 
> 

The two column looks really strange on your site. There is an setting in the host settings to switch to two column, which would look much better.

**Comment by MROSSFTEK** [comment] 2024-03-13 19:25
didnt know that.. ill check it out

**Comment by MROSSFTEK** [comment] 2024-03-13 19:39
i put the default board.ascx back in play and turned on that setting. its much nicer!

**Closed** 2024-03-16 02:31 UTC
Labels: question
