### ISSUE TITLE
cee_load keeps loading when clicking on linked image if another image attachment is in the post

### ISSUE THREAD

**Issue by j2bmw** [YAFNET/YAFNET#366] opened 2017-08-05 02:09 UTC
cee_load keeps loading when clicking on linked image if another image attachment is in the post

URL: http://bettereducation.com.au/forum/yaf_postst7155_Find-top-schools-near-your-family.aspx
Please see the issue in the video https://j2bmw.tinytake.com/sf/MTg0NTczNV81OTU3NzMz

The code
<a href="http://bettereducation.com.au/AdHandler.ashx?a=LauristonForum&amp;target=http://www.lauriston.vic.edu.au/quick-links/book-a-tour?type=bettereducation" target="_blank"><img src="http://bettereducation.com.au/Images/clients/schools/vic/lauriston/LAU024-Generic-728-x-90---1.gif"></a>

In the post, there are 1 image linked to a URL and two attached images. The linked image shows, but clicking on it, cee_load keeps spinning, as if it's trying to load an attachment, unable to navigate to target URL. Removing the attached images, it will be back normal and it works fine.

VERSION of YAF: 2.2.3, no DNN or Rainbow
hosting platform: Server Type: Microsoft-IIS/10.0, IIS187S 
.NET framework: 4

Thanks for your support and your time.
email: j2bmw@yahoo.com.au

**Comment by w8tcha** [comment] 2017-08-07 15:41
The Problem is the url with the ashx extension. Issue should be fixed in 2.2.4.2

**Closed by w8tcha** 2017-08-07 15:41 UTC
Labels: bug

**Comment by j2bmw** [comment] 2017-08-08 12:28
Thanks for such a quick response.
